services:
  angular-frontend:
    container_name: angular-frontend
    build: ./angular-frontend
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always   

  myapp-backend:
    container_name: MyAppBackend
    build: ./MyAppBackend 
    networks:
      - app-network
    restart: always  
    ports:
      - "8080:8080" 

networks:
  app-network:
    driver: bridge
